### ISSUE TITLE
Réservation chambre de conférence

### ISSUE THREAD

**Issue by romaincabassot** [pluginsGLPI/xivo#7]
Bonjour,
Une fonctionnalité que je trouverais très intéressante serait la réservation de chambre de conférence.
Romain

**Comment by orthagh** [comment]
Alors sauf erreur de ma part, cette fonctionnalité de reservation de chambre n'existe pas dans le produit xivo ou en tout cas ca ne me parle pas.

Dans le cas contraire, je veux bien un pointeur (et je ré-ouvrirais le ticket)
